//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public Nullable<int> Kitchen_ID { get; set; }
        public Nullable<int> FoodType_ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Img { get; set; }
        public string Inf { get; set; }
        public Nullable<int> Koll { get; set; }
    
        public virtual FoodType FoodType { get; set; }
        public virtual Kitchen Kitchen { get; set; }
    }
}
